### ISSUE TITLE
Create sub-tasks of the FogGuru project WP6

### ISSUE THREAD

**Issue by felipegutierrez** [felipegutierrez/robust-data-stream#6]
- [ ] Review of the state of art and analysis of parallel distributed strategies such as chaining tasks, stateless and stateful tasks and different output buffers sizes, as possibilities of implementation in a mobile edge environment.
- [ ] Design and implementation of strategies in Apache Flink, taking into account external constraints and problems inherent to mobile edge computing.
- [ ] Design of a use case or application suitable to test the implemented improvements in Apache Flink.
- [ ] Exhaustive testing under real time conditions of load and traffic.
